// app/layout.tsx
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Header from '@/components/header';
import './globals.css';

import ClerkProviderWrapper from '@/components/ClerkProviderWrapper'; // <-- nuevo wrapper client

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* ClerkProvider ahora está dentro del body y es client-only */}
        <ClerkProviderWrapper>
          <Header />
          {children}
          redirect("/calendar");

        </ClerkProviderWrapper>
      </body>
    </html>
  );
}
